version: "3"
services:
  tellform:
    image: ohmyform/ohmyform
    environment:
      CREATE_ADMIN: "TRUE"
      SOCKET_URL: 'localhost:5000'
      SOCKET_PORT: "5000"
      SOCKET_PORT_EXTERN_VISIBLE: "TRUE"
      MONGODB_URI: mongodb://mongo/tellform
      REDIS_URL: redis://redis
      MAILER_SMTP_HOST: mail
      MAILER_SMTP_PORT: 1025
    # command: grunt dev # override command to have livereloading on file change
    links:
      - mongo
      - redis
      - mail
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mail:
    image: mailhog/mailhog
    ports:
      - "5050:8025"
